/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { AdminStatsDailyActivityItem } from "./adminStatsDailyActivityItem";

export interface AdminStats {
  totalUsers: number;
  totalConversations: number;
  totalMessages: number;
  conversationsToday: number;
  usersToday: number;
  dailyActivity: AdminStatsDailyActivityItem[];
}
