/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AdminConversation,
  AdminLoginRequest,
  AdminSiteConfig,
  AdminStats,
  AdminUser,
  AuthUserEnvelope,
  CreateOpenaiConversationBody,
  ErrorEnvelope,
  HealthStatus,
  LoginRequest,
  LogoutSuccess,
  OpenaiConversation,
  OpenaiConversationWithMessages,
  OpenaiError,
  OpenaiMessage,
  RegisterRequest,
  SaveDocumentBody,
  SavedDocument,
  SendOpenaiMessageBody,
  SiteConfig,
  UpdateAdminConfig200,
  UpdateUserRoleBody,
} from "./api.schemas";

import { customFetch } from "../custom-fetch";
import type { ErrorType, BodyType } from "../custom-fetch";

type AwaitedInput<T> = PromiseLike<T> | T;

type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * @summary Health check
 */
export const getHealthCheckUrl = () => {
  return `/api/healthz`;
};

export const healthCheck = async (
  options?: RequestInit,
): Promise<HealthStatus> => {
  return customFetch<HealthStatus>(getHealthCheckUrl(), {
    ...options,
    method: "GET",
  });
};

export const getHealthCheckQueryKey = () => {
  return [`/api/healthz`] as const;
};

export const getHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getHealthCheckQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof healthCheck>>> = ({
    signal,
  }) => healthCheck({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type HealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<typeof healthCheck>>
>;
export type HealthCheckQueryError = ErrorType<unknown>;

/**
 * @summary Health check
 */

export function useHealthCheck<
  TData = Awaited<ReturnType<typeof healthCheck>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof healthCheck>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get the currently authenticated user
 */
export const getGetCurrentAuthUserUrl = () => {
  return `/api/auth/user`;
};

export const getCurrentAuthUser = async (
  options?: RequestInit,
): Promise<AuthUserEnvelope> => {
  return customFetch<AuthUserEnvelope>(getGetCurrentAuthUserUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetCurrentAuthUserQueryKey = () => {
  return [`/api/auth/user`] as const;
};

export const getGetCurrentAuthUserQueryOptions = <
  TData = Awaited<ReturnType<typeof getCurrentAuthUser>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentAuthUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetCurrentAuthUserQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getCurrentAuthUser>>
  > = ({ signal }) => getCurrentAuthUser({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentAuthUser>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetCurrentAuthUserQueryResult = NonNullable<
  Awaited<ReturnType<typeof getCurrentAuthUser>>
>;
export type GetCurrentAuthUserQueryError = ErrorType<unknown>;

/**
 * @summary Get the currently authenticated user
 */

export function useGetCurrentAuthUser<
  TData = Awaited<ReturnType<typeof getCurrentAuthUser>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getCurrentAuthUser>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetCurrentAuthUserQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Register a new user account
 */
export const getRegisterUserUrl = () => {
  return `/api/auth/register`;
};

export const registerUser = async (
  registerRequest: RegisterRequest,
  options?: RequestInit,
): Promise<AuthUserEnvelope> => {
  return customFetch<AuthUserEnvelope>(getRegisterUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(registerRequest),
  });
};

export const getRegisterUserMutationOptions = <
  TError = ErrorType<ErrorEnvelope>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    { data: BodyType<RegisterRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: BodyType<RegisterRequest> },
  TContext
> => {
  const mutationKey = ["registerUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registerUser>>,
    { data: BodyType<RegisterRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return registerUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegisterUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof registerUser>>
>;
export type RegisterUserMutationBody = BodyType<RegisterRequest>;
export type RegisterUserMutationError = ErrorType<ErrorEnvelope>;

/**
 * @summary Register a new user account
 */
export const useRegisterUser = <
  TError = ErrorType<ErrorEnvelope>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registerUser>>,
    TError,
    { data: BodyType<RegisterRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof registerUser>>,
  TError,
  { data: BodyType<RegisterRequest> },
  TContext
> => {
  return useMutation(getRegisterUserMutationOptions(options));
};

/**
 * @summary Login with email and password
 */
export const getLoginUserUrl = () => {
  return `/api/auth/login`;
};

export const loginUser = async (
  loginRequest: LoginRequest,
  options?: RequestInit,
): Promise<AuthUserEnvelope> => {
  return customFetch<AuthUserEnvelope>(getLoginUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(loginRequest),
  });
};

export const getLoginUserMutationOptions = <
  TError = ErrorType<ErrorEnvelope>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: BodyType<LoginRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  const mutationKey = ["loginUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loginUser>>,
    { data: BodyType<LoginRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return loginUser(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof loginUser>>
>;
export type LoginUserMutationBody = BodyType<LoginRequest>;
export type LoginUserMutationError = ErrorType<ErrorEnvelope>;

/**
 * @summary Login with email and password
 */
export const useLoginUser = <
  TError = ErrorType<ErrorEnvelope>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loginUser>>,
    TError,
    { data: BodyType<LoginRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof loginUser>>,
  TError,
  { data: BodyType<LoginRequest> },
  TContext
> => {
  return useMutation(getLoginUserMutationOptions(options));
};

/**
 * @summary Login as admin using environment credentials
 */
export const getAdminLoginUrl = () => {
  return `/api/auth/admin-login`;
};

export const adminLogin = async (
  adminLoginRequest: AdminLoginRequest,
  options?: RequestInit,
): Promise<AuthUserEnvelope> => {
  return customFetch<AuthUserEnvelope>(getAdminLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(adminLoginRequest),
  });
};

export const getAdminLoginMutationOptions = <
  TError = ErrorType<ErrorEnvelope>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminLogin>>,
    TError,
    { data: BodyType<AdminLoginRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof adminLogin>>,
  TError,
  { data: BodyType<AdminLoginRequest> },
  TContext
> => {
  const mutationKey = ["adminLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof adminLogin>>,
    { data: BodyType<AdminLoginRequest> }
  > = (props) => {
    const { data } = props ?? {};

    return adminLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AdminLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof adminLogin>>
>;
export type AdminLoginMutationBody = BodyType<AdminLoginRequest>;
export type AdminLoginMutationError = ErrorType<ErrorEnvelope>;

/**
 * @summary Login as admin using environment credentials
 */
export const useAdminLogin = <
  TError = ErrorType<ErrorEnvelope>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof adminLogin>>,
    TError,
    { data: BodyType<AdminLoginRequest> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof adminLogin>>,
  TError,
  { data: BodyType<AdminLoginRequest> },
  TContext
> => {
  return useMutation(getAdminLoginMutationOptions(options));
};

/**
 * @summary Logout and clear session cookie
 */
export const getLogoutUserUrl = () => {
  return `/api/auth/logout`;
};

export const logoutUser = async (
  options?: RequestInit,
): Promise<LogoutSuccess> => {
  return customFetch<LogoutSuccess>(getLogoutUserUrl(), {
    ...options,
    method: "POST",
  });
};

export const getLogoutUserMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutUser>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof logoutUser>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["logoutUser"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof logoutUser>>,
    void
  > = () => {
    return logoutUser(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LogoutUserMutationResult = NonNullable<
  Awaited<ReturnType<typeof logoutUser>>
>;

export type LogoutUserMutationError = ErrorType<unknown>;

/**
 * @summary Logout and clear session cookie
 */
export const useLogoutUser = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof logoutUser>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof logoutUser>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getLogoutUserMutationOptions(options));
};

/**
 * @summary Get public site configuration
 */
export const getGetSiteConfigUrl = () => {
  return `/api/site-config`;
};

export const getSiteConfig = async (
  options?: RequestInit,
): Promise<SiteConfig> => {
  return customFetch<SiteConfig>(getGetSiteConfigUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetSiteConfigQueryKey = () => {
  return [`/api/site-config`] as const;
};

export const getGetSiteConfigQueryOptions = <
  TData = Awaited<ReturnType<typeof getSiteConfig>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSiteConfig>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetSiteConfigQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getSiteConfig>>> = ({
    signal,
  }) => getSiteConfig({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getSiteConfig>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetSiteConfigQueryResult = NonNullable<
  Awaited<ReturnType<typeof getSiteConfig>>
>;
export type GetSiteConfigQueryError = ErrorType<unknown>;

/**
 * @summary Get public site configuration
 */

export function useGetSiteConfig<
  TData = Awaited<ReturnType<typeof getSiteConfig>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getSiteConfig>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetSiteConfigQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get dashboard stats
 */
export const getGetAdminStatsUrl = () => {
  return `/api/admin/stats`;
};

export const getAdminStats = async (
  options?: RequestInit,
): Promise<AdminStats> => {
  return customFetch<AdminStats>(getGetAdminStatsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAdminStatsQueryKey = () => {
  return [`/api/admin/stats`] as const;
};

export const getGetAdminStatsQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminStats>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminStatsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminStats>>> = ({
    signal,
  }) => getAdminStats({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAdminStatsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminStats>>
>;
export type GetAdminStatsQueryError = ErrorType<void>;

/**
 * @summary Get dashboard stats
 */

export function useGetAdminStats<
  TData = Awaited<ReturnType<typeof getAdminStats>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminStats>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAdminStatsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary List all users
 */
export const getListAdminUsersUrl = () => {
  return `/api/admin/users`;
};

export const listAdminUsers = async (
  options?: RequestInit,
): Promise<AdminUser[]> => {
  return customFetch<AdminUser[]>(getListAdminUsersUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAdminUsersQueryKey = () => {
  return [`/api/admin/users`] as const;
};

export const getListAdminUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof listAdminUsers>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAdminUsers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListAdminUsersQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listAdminUsers>>> = ({
    signal,
  }) => listAdminUsers({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAdminUsers>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAdminUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAdminUsers>>
>;
export type ListAdminUsersQueryError = ErrorType<void>;

/**
 * @summary List all users
 */

export function useListAdminUsers<
  TData = Awaited<ReturnType<typeof listAdminUsers>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAdminUsers>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAdminUsersQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update a user's role
 */
export const getUpdateUserRoleUrl = (id: string) => {
  return `/api/admin/users/${id}/role`;
};

export const updateUserRole = async (
  id: string,
  updateUserRoleBody: UpdateUserRoleBody,
  options?: RequestInit,
): Promise<AdminUser> => {
  return customFetch<AdminUser>(getUpdateUserRoleUrl(id), {
    ...options,
    method: "PATCH",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(updateUserRoleBody),
  });
};

export const getUpdateUserRoleMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserRole>>,
    TError,
    { id: string; data: BodyType<UpdateUserRoleBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserRole>>,
  TError,
  { id: string; data: BodyType<UpdateUserRoleBody> },
  TContext
> => {
  const mutationKey = ["updateUserRole"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserRole>>,
    { id: string; data: BodyType<UpdateUserRoleBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return updateUserRole(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserRoleMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserRole>>
>;
export type UpdateUserRoleMutationBody = BodyType<UpdateUserRoleBody>;
export type UpdateUserRoleMutationError = ErrorType<void>;

/**
 * @summary Update a user's role
 */
export const useUpdateUserRole = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserRole>>,
    TError,
    { id: string; data: BodyType<UpdateUserRoleBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateUserRole>>,
  TError,
  { id: string; data: BodyType<UpdateUserRoleBody> },
  TContext
> => {
  return useMutation(getUpdateUserRoleMutationOptions(options));
};

/**
 * @summary List all conversations with user info
 */
export const getListAdminConversationsUrl = () => {
  return `/api/admin/conversations`;
};

export const listAdminConversations = async (
  options?: RequestInit,
): Promise<AdminConversation[]> => {
  return customFetch<AdminConversation[]>(getListAdminConversationsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListAdminConversationsQueryKey = () => {
  return [`/api/admin/conversations`] as const;
};

export const getListAdminConversationsQueryOptions = <
  TData = Awaited<ReturnType<typeof listAdminConversations>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAdminConversations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListAdminConversationsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listAdminConversations>>
  > = ({ signal }) => listAdminConversations({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listAdminConversations>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListAdminConversationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listAdminConversations>>
>;
export type ListAdminConversationsQueryError = ErrorType<void>;

/**
 * @summary List all conversations with user info
 */

export function useListAdminConversations<
  TData = Awaited<ReturnType<typeof listAdminConversations>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listAdminConversations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListAdminConversationsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Get admin site configuration
 */
export const getGetAdminConfigUrl = () => {
  return `/api/admin/config`;
};

export const getAdminConfig = async (
  options?: RequestInit,
): Promise<AdminSiteConfig> => {
  return customFetch<AdminSiteConfig>(getGetAdminConfigUrl(), {
    ...options,
    method: "GET",
  });
};

export const getGetAdminConfigQueryKey = () => {
  return [`/api/admin/config`] as const;
};

export const getGetAdminConfigQueryOptions = <
  TData = Awaited<ReturnType<typeof getAdminConfig>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminConfig>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetAdminConfigQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getAdminConfig>>> = ({
    signal,
  }) => getAdminConfig({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getAdminConfig>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetAdminConfigQueryResult = NonNullable<
  Awaited<ReturnType<typeof getAdminConfig>>
>;
export type GetAdminConfigQueryError = ErrorType<void>;

/**
 * @summary Get admin site configuration
 */

export function useGetAdminConfig<
  TData = Awaited<ReturnType<typeof getAdminConfig>>,
  TError = ErrorType<void>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof getAdminConfig>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetAdminConfigQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Update admin site configuration
 */
export const getUpdateAdminConfigUrl = () => {
  return `/api/admin/config`;
};

export const updateAdminConfig = async (
  adminSiteConfig: AdminSiteConfig,
  options?: RequestInit,
): Promise<UpdateAdminConfig200> => {
  return customFetch<UpdateAdminConfig200>(getUpdateAdminConfigUrl(), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(adminSiteConfig),
  });
};

export const getUpdateAdminConfigMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAdminConfig>>,
    TError,
    { data: BodyType<AdminSiteConfig> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateAdminConfig>>,
  TError,
  { data: BodyType<AdminSiteConfig> },
  TContext
> => {
  const mutationKey = ["updateAdminConfig"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateAdminConfig>>,
    { data: BodyType<AdminSiteConfig> }
  > = (props) => {
    const { data } = props ?? {};

    return updateAdminConfig(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateAdminConfigMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateAdminConfig>>
>;
export type UpdateAdminConfigMutationBody = BodyType<AdminSiteConfig>;
export type UpdateAdminConfigMutationError = ErrorType<void>;

/**
 * @summary Update admin site configuration
 */
export const useUpdateAdminConfig = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateAdminConfig>>,
    TError,
    { data: BodyType<AdminSiteConfig> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof updateAdminConfig>>,
  TError,
  { data: BodyType<AdminSiteConfig> },
  TContext
> => {
  return useMutation(getUpdateAdminConfigMutationOptions(options));
};

/**
 * @summary List all saved documents for the current user
 */
export const getListDocumentsUrl = () => {
  return `/api/documents`;
};

export const listDocuments = async (
  options?: RequestInit,
): Promise<SavedDocument[]> => {
  return customFetch<SavedDocument[]>(getListDocumentsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListDocumentsQueryKey = () => {
  return [`/api/documents`] as const;
};

export const getListDocumentsQueryOptions = <
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listDocuments>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListDocumentsQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listDocuments>>> = ({
    signal,
  }) => listDocuments({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listDocuments>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListDocumentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listDocuments>>
>;
export type ListDocumentsQueryError = ErrorType<unknown>;

/**
 * @summary List all saved documents for the current user
 */

export function useListDocuments<
  TData = Awaited<ReturnType<typeof listDocuments>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listDocuments>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListDocumentsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Save a generated document record
 */
export const getSaveDocumentUrl = () => {
  return `/api/documents`;
};

export const saveDocument = async (
  saveDocumentBody: SaveDocumentBody,
  options?: RequestInit,
): Promise<SavedDocument> => {
  return customFetch<SavedDocument>(getSaveDocumentUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(saveDocumentBody),
  });
};

export const getSaveDocumentMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof saveDocument>>,
    TError,
    { data: BodyType<SaveDocumentBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof saveDocument>>,
  TError,
  { data: BodyType<SaveDocumentBody> },
  TContext
> => {
  const mutationKey = ["saveDocument"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof saveDocument>>,
    { data: BodyType<SaveDocumentBody> }
  > = (props) => {
    const { data } = props ?? {};

    return saveDocument(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SaveDocumentMutationResult = NonNullable<
  Awaited<ReturnType<typeof saveDocument>>
>;
export type SaveDocumentMutationBody = BodyType<SaveDocumentBody>;
export type SaveDocumentMutationError = ErrorType<unknown>;

/**
 * @summary Save a generated document record
 */
export const useSaveDocument = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof saveDocument>>,
    TError,
    { data: BodyType<SaveDocumentBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof saveDocument>>,
  TError,
  { data: BodyType<SaveDocumentBody> },
  TContext
> => {
  return useMutation(getSaveDocumentMutationOptions(options));
};

/**
 * @summary Delete a saved document
 */
export const getDeleteDocumentUrl = (id: number) => {
  return `/api/documents/${id}`;
};

export const deleteDocument = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteDocumentUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteDocumentMutationOptions = <
  TError = ErrorType<OpenaiError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDocument>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteDocument>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteDocument"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteDocument>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteDocument(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteDocumentMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteDocument>>
>;

export type DeleteDocumentMutationError = ErrorType<OpenaiError>;

/**
 * @summary Delete a saved document
 */
export const useDeleteDocument = <
  TError = ErrorType<OpenaiError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteDocument>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteDocument>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteDocumentMutationOptions(options));
};

/**
 * @summary List all conversations
 */
export const getListOpenaiConversationsUrl = () => {
  return `/api/openai/conversations`;
};

export const listOpenaiConversations = async (
  options?: RequestInit,
): Promise<OpenaiConversation[]> => {
  return customFetch<OpenaiConversation[]>(getListOpenaiConversationsUrl(), {
    ...options,
    method: "GET",
  });
};

export const getListOpenaiConversationsQueryKey = () => {
  return [`/api/openai/conversations`] as const;
};

export const getListOpenaiConversationsQueryOptions = <
  TData = Awaited<ReturnType<typeof listOpenaiConversations>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiConversations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getListOpenaiConversationsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listOpenaiConversations>>
  > = ({ signal }) => listOpenaiConversations({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiConversations>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListOpenaiConversationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof listOpenaiConversations>>
>;
export type ListOpenaiConversationsQueryError = ErrorType<unknown>;

/**
 * @summary List all conversations
 */

export function useListOpenaiConversations<
  TData = Awaited<ReturnType<typeof listOpenaiConversations>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiConversations>>,
    TError,
    TData
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListOpenaiConversationsQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Create a new conversation
 */
export const getCreateOpenaiConversationUrl = () => {
  return `/api/openai/conversations`;
};

export const createOpenaiConversation = async (
  createOpenaiConversationBody: CreateOpenaiConversationBody,
  options?: RequestInit,
): Promise<OpenaiConversation> => {
  return customFetch<OpenaiConversation>(getCreateOpenaiConversationUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createOpenaiConversationBody),
  });
};

export const getCreateOpenaiConversationMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOpenaiConversation>>,
    TError,
    { data: BodyType<CreateOpenaiConversationBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createOpenaiConversation>>,
  TError,
  { data: BodyType<CreateOpenaiConversationBody> },
  TContext
> => {
  const mutationKey = ["createOpenaiConversation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createOpenaiConversation>>,
    { data: BodyType<CreateOpenaiConversationBody> }
  > = (props) => {
    const { data } = props ?? {};

    return createOpenaiConversation(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateOpenaiConversationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createOpenaiConversation>>
>;
export type CreateOpenaiConversationMutationBody =
  BodyType<CreateOpenaiConversationBody>;
export type CreateOpenaiConversationMutationError = ErrorType<unknown>;

/**
 * @summary Create a new conversation
 */
export const useCreateOpenaiConversation = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createOpenaiConversation>>,
    TError,
    { data: BodyType<CreateOpenaiConversationBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof createOpenaiConversation>>,
  TError,
  { data: BodyType<CreateOpenaiConversationBody> },
  TContext
> => {
  return useMutation(getCreateOpenaiConversationMutationOptions(options));
};

/**
 * @summary Get conversation with messages
 */
export const getGetOpenaiConversationUrl = (id: number) => {
  return `/api/openai/conversations/${id}`;
};

export const getOpenaiConversation = async (
  id: number,
  options?: RequestInit,
): Promise<OpenaiConversationWithMessages> => {
  return customFetch<OpenaiConversationWithMessages>(
    getGetOpenaiConversationUrl(id),
    {
      ...options,
      method: "GET",
    },
  );
};

export const getGetOpenaiConversationQueryKey = (id: number) => {
  return [`/api/openai/conversations/${id}`] as const;
};

export const getGetOpenaiConversationQueryOptions = <
  TData = Awaited<ReturnType<typeof getOpenaiConversation>>,
  TError = ErrorType<OpenaiError>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getOpenaiConversation>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetOpenaiConversationQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getOpenaiConversation>>
  > = ({ signal }) => getOpenaiConversation(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getOpenaiConversation>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetOpenaiConversationQueryResult = NonNullable<
  Awaited<ReturnType<typeof getOpenaiConversation>>
>;
export type GetOpenaiConversationQueryError = ErrorType<OpenaiError>;

/**
 * @summary Get conversation with messages
 */

export function useGetOpenaiConversation<
  TData = Awaited<ReturnType<typeof getOpenaiConversation>>,
  TError = ErrorType<OpenaiError>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof getOpenaiConversation>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getGetOpenaiConversationQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Delete a conversation
 */
export const getDeleteOpenaiConversationUrl = (id: number) => {
  return `/api/openai/conversations/${id}`;
};

export const deleteOpenaiConversation = async (
  id: number,
  options?: RequestInit,
): Promise<void> => {
  return customFetch<void>(getDeleteOpenaiConversationUrl(id), {
    ...options,
    method: "DELETE",
  });
};

export const getDeleteOpenaiConversationMutationOptions = <
  TError = ErrorType<OpenaiError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOpenaiConversation>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteOpenaiConversation>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["deleteOpenaiConversation"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteOpenaiConversation>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return deleteOpenaiConversation(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteOpenaiConversationMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteOpenaiConversation>>
>;

export type DeleteOpenaiConversationMutationError = ErrorType<OpenaiError>;

/**
 * @summary Delete a conversation
 */
export const useDeleteOpenaiConversation = <
  TError = ErrorType<OpenaiError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteOpenaiConversation>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof deleteOpenaiConversation>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(getDeleteOpenaiConversationMutationOptions(options));
};

/**
 * @summary List messages in a conversation
 */
export const getListOpenaiMessagesUrl = (id: number) => {
  return `/api/openai/conversations/${id}/messages`;
};

export const listOpenaiMessages = async (
  id: number,
  options?: RequestInit,
): Promise<OpenaiMessage[]> => {
  return customFetch<OpenaiMessage[]>(getListOpenaiMessagesUrl(id), {
    ...options,
    method: "GET",
  });
};

export const getListOpenaiMessagesQueryKey = (id: number) => {
  return [`/api/openai/conversations/${id}/messages`] as const;
};

export const getListOpenaiMessagesQueryOptions = <
  TData = Awaited<ReturnType<typeof listOpenaiMessages>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listOpenaiMessages>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListOpenaiMessagesQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof listOpenaiMessages>>
  > = ({ signal }) => listOpenaiMessages(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!id,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof listOpenaiMessages>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type ListOpenaiMessagesQueryResult = NonNullable<
  Awaited<ReturnType<typeof listOpenaiMessages>>
>;
export type ListOpenaiMessagesQueryError = ErrorType<unknown>;

/**
 * @summary List messages in a conversation
 */

export function useListOpenaiMessages<
  TData = Awaited<ReturnType<typeof listOpenaiMessages>>,
  TError = ErrorType<unknown>,
>(
  id: number,
  options?: {
    query?: UseQueryOptions<
      Awaited<ReturnType<typeof listOpenaiMessages>>,
      TError,
      TData
    >;
    request?: SecondParameter<typeof customFetch>;
  },
): UseQueryResult<TData, TError> & { queryKey: QueryKey } {
  const queryOptions = getListOpenaiMessagesQueryOptions(id, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  return { ...query, queryKey: queryOptions.queryKey };
}

/**
 * @summary Send a text message and receive a streaming text response
 */
export const getSendOpenaiMessageUrl = (id: number) => {
  return `/api/openai/conversations/${id}/messages`;
};

export const sendOpenaiMessage = async (
  id: number,
  sendOpenaiMessageBody: SendOpenaiMessageBody,
  options?: RequestInit,
): Promise<unknown> => {
  return customFetch<unknown>(getSendOpenaiMessageUrl(id), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(sendOpenaiMessageBody),
  });
};

export const getSendOpenaiMessageMutationOptions = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendOpenaiMessage>>,
    TError,
    { id: number; data: BodyType<SendOpenaiMessageBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sendOpenaiMessage>>,
  TError,
  { id: number; data: BodyType<SendOpenaiMessageBody> },
  TContext
> => {
  const mutationKey = ["sendOpenaiMessage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sendOpenaiMessage>>,
    { id: number; data: BodyType<SendOpenaiMessageBody> }
  > = (props) => {
    const { id, data } = props ?? {};

    return sendOpenaiMessage(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SendOpenaiMessageMutationResult = NonNullable<
  Awaited<ReturnType<typeof sendOpenaiMessage>>
>;
export type SendOpenaiMessageMutationBody = BodyType<SendOpenaiMessageBody>;
export type SendOpenaiMessageMutationError = ErrorType<unknown>;

/**
 * @summary Send a text message and receive a streaming text response
 */
export const useSendOpenaiMessage = <
  TError = ErrorType<unknown>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sendOpenaiMessage>>,
    TError,
    { id: number; data: BodyType<SendOpenaiMessageBody> },
    TContext
  >;
  request?: SecondParameter<typeof customFetch>;
}): UseMutationResult<
  Awaited<ReturnType<typeof sendOpenaiMessage>>,
  TError,
  { id: number; data: BodyType<SendOpenaiMessageBody> },
  TContext
> => {
  return useMutation(getSendOpenaiMessageMutationOptions(options));
};
