/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export type AuthUserRole = (typeof AuthUserRole)[keyof typeof AuthUserRole];

export const AuthUserRole = {
  user: "user",
  admin: "admin",
  special: "special",
} as const;

export interface AuthUser {
  id: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  profileImageUrl: string | null;
  role: AuthUserRole;
}

export interface AuthUserEnvelope {
  user: AuthUser | null;
}

export interface RegisterRequest {
  email: string;
  /** @minLength 6 */
  password: string;
  /** @minLength 1 */
  firstName: string;
  lastName?: string;
}

export interface LoginRequest {
  email: string;
  password: string;
}

export interface AdminLoginRequest {
  username: string;
  password: string;
}

export const LogoutSuccessValue = {
  success: true,
} as const;
export type LogoutSuccess = typeof LogoutSuccessValue;

export interface ErrorEnvelope {
  error: string;
}

export interface SiteConfig {
  welcomeMessage: string;
  primaryColor: string;
}

export interface AdminSiteConfig {
  systemPrompt: string;
  welcomeMessage: string;
  primaryColor: string;
}

export type AdminStatsDailyActivityItem = {
  date: string;
  conversations: number;
  messages: number;
};

export interface AdminStats {
  totalUsers: number;
  totalConversations: number;
  totalMessages: number;
  conversationsToday: number;
  usersToday: number;
  dailyActivity: AdminStatsDailyActivityItem[];
}

export type AdminUserRole = (typeof AdminUserRole)[keyof typeof AdminUserRole];

export const AdminUserRole = {
  user: "user",
  admin: "admin",
  special: "special",
} as const;

export interface AdminUser {
  id: string;
  /** @nullable */
  email: string | null;
  /** @nullable */
  firstName: string | null;
  /** @nullable */
  lastName: string | null;
  /** @nullable */
  profileImageUrl: string | null;
  role: AdminUserRole;
  createdAt: string;
  conversationCount: number;
}

export type UpdateUserRoleBodyRole =
  (typeof UpdateUserRoleBodyRole)[keyof typeof UpdateUserRoleBodyRole];

export const UpdateUserRoleBodyRole = {
  user: "user",
  admin: "admin",
  special: "special",
} as const;

export interface UpdateUserRoleBody {
  role: UpdateUserRoleBodyRole;
}

export interface AdminConversation {
  id: number;
  title: string;
  createdAt: string;
  messageCount: number;
  /** @nullable */
  userId: string | null;
  /** @nullable */
  userEmail: string | null;
}

export interface OpenaiConversation {
  id: number;
  title: string;
  createdAt: string;
}

export interface OpenaiMessage {
  id: number;
  conversationId: number;
  role: string;
  content: string;
  createdAt: string;
}

export interface CreateOpenaiConversationBody {
  title: string;
}

export interface SendOpenaiMessageBody {
  content: string;
}

export interface OpenaiConversationWithMessages {
  id: number;
  title: string;
  createdAt: string;
  messages: OpenaiMessage[];
}

export interface OpenaiError {
  error: string;
}

export type SavedDocumentFileType =
  (typeof SavedDocumentFileType)[keyof typeof SavedDocumentFileType];

export const SavedDocumentFileType = {
  pdf: "pdf",
  excel: "excel",
  word: "word",
  ppt: "ppt",
} as const;

export interface SavedDocument {
  id: number;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  conversationId?: string | null;
  title: string;
  fileType: SavedDocumentFileType;
  content: string;
  createdAt: string;
}

export type SaveDocumentBodyFileType =
  (typeof SaveDocumentBodyFileType)[keyof typeof SaveDocumentBodyFileType];

export const SaveDocumentBodyFileType = {
  pdf: "pdf",
  excel: "excel",
  word: "word",
  ppt: "ppt",
} as const;

export interface SaveDocumentBody {
  title: string;
  fileType: SaveDocumentBodyFileType;
  content: string;
  /** @nullable */
  conversationId?: string | null;
}

export type UpdateAdminConfig200 = {
  success: boolean;
};
