/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { SavedDocumentFileType } from "./savedDocumentFileType";

export interface SavedDocument {
  id: number;
  /** @nullable */
  userId?: string | null;
  /** @nullable */
  conversationId?: string | null;
  title: string;
  fileType: SavedDocumentFileType;
  content: string;
  createdAt: Date;
}
