/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type SaveDocumentBodyFileType =
  (typeof SaveDocumentBodyFileType)[keyof typeof SaveDocumentBodyFileType];

export const SaveDocumentBodyFileType = {
  pdf: "pdf",
  excel: "excel",
  word: "word",
  ppt: "ppt",
} as const;
