import { useCallback } from "react";

export type DocType = "pdf" | "excel" | "word" | "ppt";

const DOC_MARKER = "📄 DOCUMENT:";
const END_MARKER = "---END DOCUMENT---";

function extractDocumentContent(text: string): { title: string; body: string } {
  const start = text.indexOf(DOC_MARKER);
  if (start === -1) return { title: "SANSA Document", body: text };
  const titleEnd = text.indexOf("\n", start);
  const title = text.slice(start + DOC_MARKER.length, titleEnd).trim() || "SANSA Document";
  const end = text.indexOf(END_MARKER, titleEnd);
  const body = (end !== -1 ? text.slice(titleEnd + 1, end) : text.slice(titleEnd + 1)).trim();
  return { title, body };
}

function parseMarkdownTable(markdown: string): string[][] | null {
  const rows: string[][] = [];
  for (const line of markdown.split("\n")) {
    if (!line.includes("|")) continue;
    if (/^\|[\s:-]+\|/.test(line)) continue;
    const cells = line.split("|").map((c) => c.trim()).filter(Boolean);
    if (cells.length > 1) rows.push(cells);
  }
  return rows.length >= 2 ? rows : null;
}

function isNumeric(val: string) {
  return !isNaN(Number(val.replace(/[₹,$,%\s]/g, ""))) && val.trim() !== "";
}

async function autoSaveDocument(
  title: string,
  fileType: DocType,
  content: string,
  conversationId?: string | null,
) {
  try {
    await fetch("/api/documents", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      credentials: "include",
      body: JSON.stringify({ title, fileType, content, conversationId: conversationId ?? null }),
    });
  } catch {
    // Silently ignore save errors — download still proceeds
  }
}

interface DocumentGeneratorOptions {
  conversationId?: string | null;
  autoSave?: boolean;
}

export function useDocumentGenerator(
  conversationIdOrOptions?: string | null | DocumentGeneratorOptions,
) {
  const options: DocumentGeneratorOptions =
    typeof conversationIdOrOptions === "object" && conversationIdOrOptions !== null && "autoSave" in conversationIdOrOptions
      ? conversationIdOrOptions
      : { conversationId: conversationIdOrOptions as string | null | undefined };

  const { conversationId, autoSave = true } = options;

  const hasDocument = useCallback((text: string): boolean => {
    return text.includes(DOC_MARKER);
  }, []);

  // ─── PDF ────────────────────────────────────────────────────────────────────
  const downloadPDF = useCallback(async (text: string) => {
    const { title, body } = extractDocumentContent(text);
    const { jsPDF } = await import("jspdf");

    const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
    const W = pdf.internal.pageSize.getWidth();
    const H = pdf.internal.pageSize.getHeight();
    const ML = 15, MR = 15, MT = 15;
    const usable = W - ML - MR;
    let y = MT;

    const newPageIfNeeded = (needed = 8) => {
      if (y + needed > H - 18) { pdf.addPage(); y = MT; }
    };

    pdf.setFillColor(20, 20, 20);
    pdf.rect(0, 0, W, 28, "F");
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(16);
    pdf.setFont("helvetica", "bold");
    const titleLines = pdf.splitTextToSize(title, usable);
    pdf.text(titleLines, ML, 12);
    pdf.setFontSize(8);
    pdf.setFont("helvetica", "normal");
    pdf.text("Generated by SANSA AI", ML, 24);
    y = 36;

    pdf.setTextColor(30, 30, 30);

    const tableRows = parseMarkdownTable(body);

    if (tableRows && tableRows.length >= 2) {
      const headers = tableRows[0];
      const dataRows = tableRows.slice(1);
      const colW = usable / headers.length;

      newPageIfNeeded(10);
      pdf.setFillColor(40, 40, 40);
      pdf.rect(ML, y, usable, 8, "F");
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(9);
      pdf.setFont("helvetica", "bold");
      headers.forEach((h, i) => {
        pdf.text(h, ML + i * colW + 2, y + 5.5, { maxWidth: colW - 4 });
      });
      y += 8;

      pdf.setFont("helvetica", "normal");
      dataRows.forEach((row, ri) => {
        newPageIfNeeded(7);
        pdf.setFillColor(ri % 2 === 0 ? 245 : 255, ri % 2 === 0 ? 245 : 255, ri % 2 === 0 ? 245 : 255);
        pdf.rect(ML, y, usable, 7, "F");
        pdf.setTextColor(30, 30, 30);
        row.forEach((cell, i) => {
          const align = isNumeric(cell) ? "right" : "left";
          const x = align === "right" ? ML + (i + 1) * colW - 3 : ML + i * colW + 2;
          pdf.text(cell, x, y + 4.8, { align, maxWidth: colW - 4 });
        });
        y += 7;
      });

      pdf.setDrawColor(200, 200, 200);
      pdf.rect(ML, 36, usable, y - 36, "S");
      y += 6;

    } else {
      for (const line of body.split("\n")) {
        const stripped = line.replace(/\*\*/g, "").trim();
        if (!stripped) { y += 3; continue; }

        if (/^#{1,2}\s/.test(line)) {
          newPageIfNeeded(10);
          pdf.setFontSize(13);
          pdf.setFont("helvetica", "bold");
          pdf.setTextColor(20, 20, 20);
          const h = pdf.splitTextToSize(stripped.replace(/^#+\s/, ""), usable);
          pdf.text(h, ML, y);
          y += h.length * 6 + 3;
          pdf.setFontSize(10);
          pdf.setFont("helvetica", "normal");
          pdf.setTextColor(30, 30, 30);

        } else if (/^###\s/.test(line)) {
          newPageIfNeeded(8);
          pdf.setFontSize(11);
          pdf.setFont("helvetica", "bold");
          const h = pdf.splitTextToSize(stripped.replace(/^###\s/, ""), usable);
          pdf.text(h, ML, y);
          y += h.length * 5.5 + 2;
          pdf.setFontSize(10);
          pdf.setFont("helvetica", "normal");

        } else if (/^[-*]\s/.test(line)) {
          newPageIfNeeded(6);
          const bullet = "• " + stripped.replace(/^[-*]\s/, "");
          const wrapped = pdf.splitTextToSize(bullet, usable - 5);
          pdf.text(wrapped, ML + 5, y);
          y += wrapped.length * 5 + 1;

        } else {
          newPageIfNeeded(6);
          const wrapped = pdf.splitTextToSize(stripped, usable);
          pdf.text(wrapped, ML, y);
          y += wrapped.length * 5 + 1;
        }
      }
    }

    const pageCount = (pdf as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(7);
      pdf.setFont("helvetica", "italic");
      pdf.setTextColor(150, 150, 150);
      pdf.line(ML, H - 12, W - MR, H - 12);
      pdf.text("SANSA AI  ·  sansaassistants.com", ML, H - 7);
      pdf.text(`Page ${i} of ${pageCount}`, W - MR, H - 7, { align: "right" });
    }

    pdf.save(`${title.replace(/[^a-z0-9]/gi, "_")}.pdf`);
    if (autoSave) await autoSaveDocument(title, "pdf", text, conversationId);
  }, [conversationId, autoSave]);

  // ─── EXCEL ──────────────────────────────────────────────────────────────────
  const downloadExcel = useCallback(async (text: string) => {
    const { title, body } = extractDocumentContent(text);
    const XLSX = await import("xlsx");

    let wsData: (string | number)[][];
    const tableRows = parseMarkdownTable(body);

    if (tableRows && tableRows.length >= 2) {
      wsData = tableRows.map((row, ri) =>
        row.map((cell) => {
          if (ri === 0) return cell;
          const num = Number(cell.replace(/[₹,$,%\s]/g, ""));
          return !isNaN(num) && cell.trim() !== "" ? num : cell;
        })
      );
    } else {
      wsData = body
        .split("\n")
        .filter((l) => l.trim())
        .map((l) => [l.replace(/^[#*-]\s*/, "").replace(/\*\*/g, "").trim()]);
    }

    const wb = XLSX.utils.book_new();
    const ws = XLSX.utils.aoa_to_sheet(wsData);

    if (tableRows && wsData.length > 0) {
      const cols = wsData[0].length;
      for (let c = 0; c < cols; c++) {
        const cellAddr = XLSX.utils.encode_cell({ r: 0, c });
        if (!ws[cellAddr]) continue;
        ws[cellAddr].s = {
          font: { bold: true, color: { rgb: "FFFFFF" } },
          fill: { patternType: "solid", fgColor: { rgb: "141414" } },
          alignment: { horizontal: "center" },
        };
      }
    }

    const colWidths = wsData[0]?.map((_, ci) =>
      Math.max(...wsData.map((row) => String(row[ci] ?? "").length)) + 4
    );
    if (colWidths) ws["!cols"] = colWidths.map((w) => ({ wch: Math.min(w, 40) }));

    XLSX.utils.book_append_sheet(wb, ws, title.slice(0, 31));
    XLSX.writeFile(wb, `${title.replace(/[^a-z0-9]/gi, "_")}.xlsx`);
    if (autoSave) await autoSaveDocument(title, "excel", text, conversationId);
  }, [conversationId, autoSave]);

  // ─── WORD ───────────────────────────────────────────────────────────────────
  const downloadWord = useCallback(async (text: string) => {
    const { title, body } = extractDocumentContent(text);
    const {
      Document, Packer, Paragraph, TextRun, HeadingLevel,
      AlignmentType, Table, TableRow, TableCell, WidthType,
      BorderStyle, ShadingType,
    } = await import("docx");

    const children: (Paragraph | Table)[] = [];

    children.push(
      new Paragraph({
        children: [new TextRun({ text: title, bold: true, size: 36 })],
        alignment: AlignmentType.CENTER,
        spacing: { after: 200 },
      }),
      new Paragraph({
        children: [new TextRun({ text: "Generated by SANSA AI  ·  sansaassistants.com", italics: true, size: 16, color: "888888" })],
        alignment: AlignmentType.CENTER,
        spacing: { after: 400 },
      })
    );

    const tableRows = parseMarkdownTable(body);

    if (tableRows && tableRows.length >= 2) {
      const headers = tableRows[0];
      const dataRows = tableRows.slice(1);
      const colCount = headers.length;
      const colPct = Math.floor(100 / colCount);

      const headerCells = headers.map((h) =>
        new TableCell({
          children: [new Paragraph({
            children: [new TextRun({ text: h, bold: true, color: "FFFFFF", size: 20 })],
            alignment: AlignmentType.CENTER,
          })],
          shading: { type: ShadingType.SOLID, color: "141414", fill: "141414" },
          width: { size: colPct, type: WidthType.PERCENTAGE },
        })
      );

      const bodyRows = dataRows.map((row, ri) =>
        new TableRow({
          children: row.map((cell) =>
            new TableCell({
              children: [new Paragraph({
                children: [new TextRun({ text: cell, size: 18 })],
                alignment: isNumeric(cell) ? AlignmentType.RIGHT : AlignmentType.LEFT,
              })],
              shading: ri % 2 === 0
                ? { type: ShadingType.SOLID, color: "F5F5F5", fill: "F5F5F5" }
                : undefined,
              width: { size: colPct, type: WidthType.PERCENTAGE },
            })
          ),
        })
      );

      children.push(
        new Table({
          rows: [new TableRow({ children: headerCells }), ...bodyRows],
          width: { size: 100, type: WidthType.PERCENTAGE },
        })
      );
    } else {
      for (const line of body.split("\n")) {
        const stripped = line.replace(/\*\*/g, "").trim();
        if (!stripped) {
          children.push(new Paragraph({ text: "" }));
        } else if (/^# /.test(line)) {
          children.push(new Paragraph({ text: stripped.replace(/^# /, ""), heading: HeadingLevel.HEADING_1 }));
        } else if (/^## /.test(line)) {
          children.push(new Paragraph({ text: stripped.replace(/^## /, ""), heading: HeadingLevel.HEADING_2 }));
        } else if (/^### /.test(line)) {
          children.push(new Paragraph({ text: stripped.replace(/^### /, ""), heading: HeadingLevel.HEADING_3 }));
        } else if (/^[-*] /.test(line)) {
          children.push(new Paragraph({
            children: [new TextRun({ text: stripped.replace(/^[-*] /, ""), size: 22 })],
            bullet: { level: 0 },
          }));
        } else {
          children.push(new Paragraph({
            children: [new TextRun({ text: stripped, size: 22 })],
            spacing: { after: 80 },
          }));
        }
      }
    }

    const wordDoc = new Document({ sections: [{ children }] });
    const blob = await Packer.toBlob(wordDoc);
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/[^a-z0-9]/gi, "_")}.docx`;
    a.click();
    URL.revokeObjectURL(url);
    if (autoSave) await autoSaveDocument(title, "word", text, conversationId);
  }, [conversationId, autoSave]);

  // ─── PPT ────────────────────────────────────────────────────────────────────
  const downloadPPT = useCallback(async (text: string) => {
    const { title, body } = extractDocumentContent(text);
    const PptxGenJS = (await import("pptxgenjs")).default;
    const prs = new PptxGenJS();

    prs.layout = "LAYOUT_WIDE";

    // ── Cover slide ──
    const cover = prs.addSlide();
    cover.background = { color: "141414" };
    cover.addText("SANSA AI", {
      x: 0.5, y: 1.8, w: 12.33, h: 0.8,
      fontSize: 36, bold: true, color: "FFFFFF",
      align: "center",
    });
    cover.addText(title, {
      x: 0.5, y: 2.8, w: 12.33, h: 1.2,
      fontSize: 24, color: "CCCCCC",
      align: "center", wrap: true,
    });
    cover.addText("Generated by SANSA AI  ·  sansaassistants.com", {
      x: 0.5, y: 6.6, w: 12.33, h: 0.4,
      fontSize: 11, color: "888888",
      align: "center",
    });

    // Split body into sections on ## headings
    // Each section starts with an optional ## heading line
    const rawSections = body.split(/(?=^## )/m).filter((s) => s.trim());

    for (const section of rawSections) {
      const lines = section.split("\n");
      const headingLine = lines[0];
      const heading = headingLine.replace(/^#+\s*/, "").trim();
      const contentLines = lines.slice(1);

      const slide = prs.addSlide();
      slide.background = { color: "FFFFFF" };

      if (heading) {
        slide.addText(heading, {
          x: 0.5, y: 0.2, w: 12.33, h: 0.65,
          fontSize: 22, bold: true, color: "141414",
        });
      }

      // Check if this section's content contains a markdown table
      const sectionContent = contentLines.join("\n");
      const tableRows = parseMarkdownTable(sectionContent);

      if (tableRows && tableRows.length >= 2) {
        const headers = tableRows[0];
        const dataRowsPPT = tableRows.slice(1);
        const colW = 12.33 / headers.length;

        const tableData: { text: string; options: { bold?: boolean; color?: string; fill?: string; align?: "left" | "center" | "right" } }[][] = [
          headers.map((h) => ({
            text: h,
            options: {
              bold: true,
              color: "FFFFFF",
              fill: "141414",
              align: "center" as const,
            },
          })),
          ...dataRowsPPT.map((row, ri) =>
            row.map((cell) => ({
              text: cell,
              options: {
                fill: ri % 2 === 0 ? "F5F5F5" : "FFFFFF",
                align: (isNumeric(cell) ? "right" : "left") as "right" | "left",
              },
            }))
          ),
        ];

        slide.addTable(tableData, {
          x: 0.5, y: heading ? 1.05 : 0.3, w: 12.33,
          fontSize: 11,
          border: { type: "solid", color: "DDDDDD", pt: 0.5 },
          colW: headers.map(() => colW),
        });
      } else {
        // Render bullets / text lines
        const bullets = contentLines
          .map((l) => l.replace(/^[-*]\s*/, "").replace(/^#+\s*/, "").replace(/\*\*/g, "").trim())
          .filter(Boolean);

        if (bullets.length > 0) {
          const bulletObjs = bullets.map((b) => ({ text: b, options: { bullet: true } }));
          slide.addText(bulletObjs, {
            x: 0.5, y: heading ? 1.1 : 0.3, w: 12.33, h: 5.8,
            fontSize: 14, color: "333333",
            valign: "top", wrap: true,
          });
        }
      }

      // Footer
      slide.addText("SANSA AI", {
        x: 0.5, y: 7.1, w: 12.33, h: 0.3,
        fontSize: 9, color: "AAAAAA", align: "right",
      });
    }

    await prs.writeFile({ fileName: `${title.replace(/[^a-z0-9]/gi, "_")}.pptx` });
    if (autoSave) await autoSaveDocument(title, "ppt", text, conversationId);
  }, [conversationId, autoSave]);

  return { hasDocument, downloadPDF, downloadExcel, downloadWord, downloadPPT };
}
